baseURL: https://example.com
languageCode: en-us
title: Melrick Mascarenhas
theme: vanilla-bootstrap-hugo-theme


taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Blog
    pre: edit
    url: /posts/
    weight: 2
  - name: About
    pre: smile
    url: /about/
    weight: 3
  - name: Resume
    pre: paperclip
    url: /resume/
    weight: 4
  - name: Contact Me
    pre: send
    url: /contact/
    weight:


params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: Hey there! Welcome to my corner of the internet. I plan to use this page to write blogs and document my journey as a Software Engineer.
   Please send motivation:)
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
